@hostname=localhost
@port=8000

POST http://{{hostname}}:{{port}}/batch HTTP/1.1
Content-Type: multipart/form-data; boundary=WebKitFormBoundary

--WebKitFormBoundary
Content-Disposition: form-data; name="batch_name"

test_batch_1
--WebKitFormBoundary
Content-Disposition: form-data; name="workflow_id"

e1d7ffef-508e-46c3-bc94-19426f0142e8
--WebKitFormBoundary
Content-Disposition: form-data; name="user_id"

test_user_1
--WebKitFormBoundary
Content-Disposition: form-data; name="repo_screenshot"; filename="repo_screenshot_2.jpg"
Content-Type: image/jpg

< ./repo_screenshot_2.jpg
--WebKitFormBoundary