@hostname=localhost
@port=8080

POST http://{{hostname}}:{{port}}/workflows HTTP/1.1
Content-Type: application/json

{
    "is_full_page_recognition": "true",
    "skip_img_enchancement": "false",
    "expect_diff_images": "false"
}