@hostname=localhost
@port=8080

POST http://{{hostname}}:{{port}}/workflows HTTP/1.1

{
    "is_full_page_recognition": "true",
    "skip_img_enhancement": "false",
    "expect_diff_images": "false"
}